"""Ajout du champ status au modèle Manga

Revision ID: 23980535f0b1
Revises: 9e919bdb21ec
Create Date: 2025-08-20 11:43:21.591740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23980535f0b1'
down_revision = '9e919bdb21ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('manga', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.drop_column('status_badge')
        batch_op.drop_column('date_added')
        batch_op.drop_column('status_progress')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('manga', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status_progress', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('date_added', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('status_badge', sa.VARCHAR(length=20), nullable=True))
        batch_op.drop_column('status')

    # ### end Alembic commands ###
