"""Recréation des migrations

Revision ID: 515db429ed51
Revises: 7aa1ed8b5aa9
Create Date: 2025-08-26 19:22:59.635259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '515db429ed51'
down_revision = '7aa1ed8b5aa9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reading_progress')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reading_progress',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('manga_id', sa.INTEGER(), nullable=False),
    sa.Column('chapter_name', sa.VARCHAR(length=120), nullable=False),
    sa.Column('last_read_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['manga_id'], ['manga.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
