"""Ajout du champ is_hot au modèle Manga

Revision ID: 52936fe9ed4b
Revises: 
Create Date: 2025-07-19 16:10:35.124980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52936fe9ed4b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('manga', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_hot', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('manga', schema=None) as batch_op:
        batch_op.drop_column('is_hot')

    # ### end Alembic commands ###
