"""Ajout de la colonne images au modèle Chapter

Revision ID: 890c12cebc00
Revises: f864b2beb72c
Create Date: 2025-09-07 13:35:24.390488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '890c12cebc00'
down_revision = 'f864b2beb72c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chapter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('images', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chapter', schema=None) as batch_op:
        batch_op.drop_column('images')

    # ### end Alembic commands ###
