"""Ajout du champ status au modèle Manga

Revision ID: 89ac1b233fc1
Revises: e2ed2b53aea2
Create Date: 2025-08-20 10:09:00.356614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89ac1b233fc1'
down_revision = 'e2ed2b53aea2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('manga', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('manga', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
