"""Ajout des champs status_progress et status_badge au modèle Manga

Revision ID: 9e919bdb21ec
Revises: 89ac1b233fc1
Create Date: 2025-08-20 10:44:31.715196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e919bdb21ec'
down_revision = '89ac1b233fc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('manga', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status_progress', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('status_badge', sa.String(length=20), nullable=True))
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('manga', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=20), nullable=True))
        batch_op.drop_column('status_badge')
        batch_op.drop_column('status_progress')

    # ### end Alembic commands ###
