"""Ajout des champs is_hot, is_new, is_top au modèle Manga

Revision ID: a0c521cbec46
Revises: 52936fe9ed4b
Create Date: 2025-07-22 15:56:50.293577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0c521cbec46'
down_revision = '52936fe9ed4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('manga', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_new', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_top', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('manga', schema=None) as batch_op:
        batch_op.drop_column('is_top')
        batch_op.drop_column('is_new')

    # ### end Alembic commands ###
