"""Ajout du champ views au modèle Manga

Revision ID: e2ed2b53aea2
Revises: 790f29653ded
Create Date: 2025-08-19 15:45:33.944805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2ed2b53aea2'
down_revision = '790f29653ded'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('manga', schema=None) as batch_op:
        batch_op.add_column(sa.Column('views', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('manga', schema=None) as batch_op:
        batch_op.drop_column('views')

    # ### end Alembic commands ###
