"""Ajout du champ status au modèle Manga

Revision ID: e55a2363e30d
Revises: 23980535f0b1
Create Date: 2025-08-20 11:47:26.797814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e55a2363e30d'
down_revision = '23980535f0b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('manga', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_added', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('manga', schema=None) as batch_op:
        batch_op.drop_column('date_added')

    # ### end Alembic commands ###
