"""Fix ReadingHistory composite primary key

Revision ID: f864b2beb72c
Revises: ff91fa5d290b
Create Date: 2025-08-29 15:12:09.255964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f864b2beb72c'
down_revision = 'ff91fa5d290b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reading_history', schema=None) as batch_op:
        batch_op.alter_column('chapter_name',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=120),
               nullable=False)
        batch_op.drop_column('id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reading_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), nullable=False))
        batch_op.alter_column('chapter_name',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=128),
               nullable=True)

    # ### end Alembic commands ###
